<a href="https://colab.research.google.com/github/Mimohamed1998/Ass_1/blob/main/matrix_based_implementation_v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Customer Configurations

In [103]:
customer_cap  = 2
l_status = 3

# Create the dummay dataframe

In [104]:
import numpy as np

In [105]:
import pandas as pd
import random

# Constants
NUM_WINGS = 5
MIN_ROOMS_PER_WING = 3
MAX_ROOMS_PER_WING = 5
NORMAL_ROOMS = 4
LUXURY_ROOMS = 1

# Function to generate random luxury status and energy cost
def generate_luxury_status():
    luxury_status = random.choice([1,2,3])
    if luxury_status == 1:
        return luxury_status, random.randint(70, 100)
    elif luxury_status == 2:
        return luxury_status, random.randint(90, 120)
    else:
        return luxury_status, random.randint(110, 130)

# Initialize lists for DataFrame columns
room_numbers = []
per_room_energy_costs = []
wing_numbers = []
luxury_statuses = []
room_capacities = []

# Create DataFrame
for wing in range(NUM_WINGS):
    wing_rooms = random.randint(MIN_ROOMS_PER_WING, MAX_ROOMS_PER_WING)
    for room in range(1, wing_rooms + 1):
        room_number = room
        luxury_status, energy_cost = generate_luxury_status()
        room_capacity = random.choice([2, 3])

        room_numbers.append(room_number)
        per_room_energy_costs.append(energy_cost)
        wing_numbers.append(chr(ord('A') + wing))
        luxury_statuses.append(luxury_status)
        room_capacities.append(room_capacity)

# Create DataFrame
data = {
    'Room_Number': room_numbers,
    'Per_Room_Energy_Cost': per_room_energy_costs,
    'Wing_Number': wing_numbers,
    'Luxury_Status': luxury_statuses,
    'Room_Capacity': room_capacities
}

hotel_df = pd.DataFrame(data)

# Display the DataFrame
print(hotel_df)


    Room_Number  Per_Room_Energy_Cost Wing_Number  Luxury_Status  \
0             1                   110           A              3   
1             2                   105           A              2   
2             3                    96           A              2   
3             4                    78           A              1   
4             5                   125           A              3   
5             1                   113           B              3   
6             2                   107           B              2   
7             3                   106           B              2   
8             4                   110           B              3   
9             1                    78           C              1   
10            2                    82           C              1   
11            3                    89           C              1   
12            4                    82           C              1   
13            5                    90           

## Testing the dataframe

In [106]:
hotel_df[hotel_df['Room_Number']==1]

Room_Number  Per_Room_Energy_Cost Wing_Number  Luxury_Status  \
0             1                   110           A              3   
5             1                   113           B              3   
9             1                    78           C              1   
14            1                    96           D              2   
19            1                   110           E              3   

    Room_Capacity  
0               2  
5               3  
9               2  
14              2  
19              3

In [107]:
hotel_df[hotel_df['Wing_Number']=='B'].count()

Room_Number             4
Per_Room_Energy_Cost    4
Wing_Number             4
Luxury_Status           4
Room_Capacity           4
dtype: int64

In [108]:
hotel_df[hotel_df['Room_Capacity']==2].count()

Room_Number             15
Per_Room_Energy_Cost    15
Wing_Number             15
Luxury_Status           15
Room_Capacity           15
dtype: int64

## Create the wing datafrma

In [109]:
import pandas as pd
import random

# Constants
NUM_WINGS = NUM_WINGS
MIN_WING_COST = 300
MAX_WING_COST = 350

# Initialize lists for DataFrame columns
wing_numbers = []
wing_costs = []

# Create DataFrame for wing information
for wing in range(NUM_WINGS):
    wing_number = chr(ord('A') + wing)
    wing_cost = random.uniform(MIN_WING_COST, MAX_WING_COST)

    wing_numbers.append(wing_number)
    wing_costs.append(wing_cost)

# Create DataFrame
wing_data = {
    'Wing_Number': wing_numbers,
    'Wing_Cost': wing_costs
}

wing_df = pd.DataFrame(wing_data)

# Display the DataFrame
print(wing_df)


  Wing_Number   Wing_Cost
0           A  342.830735
1           B  337.523495
2           C  328.270524
3           D  310.831277
4           E  308.469790


# pre process metric

In [110]:
hotel_df['status'] = True

In [111]:
# Find wing with the highest number of rooms
wing_max_rooms = hotel_df.groupby('Wing_Number')['Room_Number'].count().max()
wing_max_rooms

5

In [112]:
# Create DataFrame with rows from 0 to max_rooms_per_wing
rooms_df = pd.DataFrame({'Room_Number': range(wing_max_rooms )})
rooms_df['Room_Number'] = rooms_df['Room_Number']+1

In [113]:
cross_joined_df = pd.merge(wing_df[['Wing_Number']].assign(key=1), rooms_df.assign(key=1), on='key').drop('key', axis=1)

cross_joined_df

Wing_Number  Room_Number
0            A            1
1            A            2
2            A            3
3            A            4
4            A            5
5            B            1
6            B            2
7            B            3
8            B            4
9            B            5
10           C            1
11           C            2
12           C            3
13           C            4
14           C            5
15           D            1
16           D            2
17           D            3
18           D            4
19           D            5
20           E            1
21           E            2
22           E            3
23           E            4
24           E            5

In [114]:
# Perform left join with cross_joined_df and fill subset with 65,535
hotel_df_processed = pd.merge(cross_joined_df, hotel_df, on=['Wing_Number', 'Room_Number'], how='left')
# hotel_df_processed['Per_Room Energy_Cost'] = hotel_df_processed['Per_Room_Energy_Cost'].fillna(65535)
hotel_df_processed['Luxury_Status'] = hotel_df_processed['Luxury_Status'].fillna(0)
hotel_df_processed['Room_Capacity'] = hotel_df_processed['Room_Capacity'].fillna(0)
hotel_df_processed['status'] = hotel_df_processed['status'].fillna(False)

# hotel_df_processed = hotel_df_processed.sort('Room Number')

# Display the resulting hotel DataFrame
print("\nHotel DataFrame:")
hotel_df_processed


Hotel DataFrame:


Wing_Number  Room_Number  Per_Room_Energy_Cost  Luxury_Status  \
0            A            1                 110.0            3.0   
1            A            2                 105.0            2.0   
2            A            3                  96.0            2.0   
3            A            4                  78.0            1.0   
4            A            5                 125.0            3.0   
5            B            1                 113.0            3.0   
6            B            2                 107.0            2.0   
7            B            3                 106.0            2.0   
8            B            4                 110.0            3.0   
9            B            5                   NaN            0.0   
10           C            1                  78.0            1.0   
11           C            2                  82.0            1.0   
12           C            3                  89.0            1.0   
13           C            4                  82.0            1.0   
14           C            5                  90.0            1.0   
15           D            1                  96.0            2.0   
16           D            2                  75.0            1.0   
17           D            3                 117.0            2.0   
18           D            4                 119.0            3.0   
19           D            5                 115.0            3.0   
20           E            1                 110.0            3.0   
21           E            2                  99.0            2.0   
22           E            3                  71.0            1.0   
23           E            4                 113.0            2.0   
24           E            5                   NaN            0.0   

    Room_Capacity  status  
0             2.0    True  
1             2.0    True  
2             2.0    True  
3             2.0    True  
4             3.0    True  
5             3.0    True  
6             2.0    True  
7             3.0    True  
8             2.0    True  
9             0.0   False  
10            2.0    True  
11            3.0    True  
12            3.0    True  
13            3.0    True  
14            2.0    True  
15            2.0    True  
16            2.0    True  
17            2.0    True  
18            2.0    True  
19            2.0    True  
20            3.0    True  
21            3.0    True  
22            2.0    True  
23            2.0    True  
24            0.0   False

In [115]:
# Sort the DataFrame by 'Wing Number' and 'Room Number'
hotel_df_processed = hotel_df_processed.sort_values(by=['Wing_Number', 'Room_Number'])
hotel_df_processed

Wing_Number  Room_Number  Per_Room_Energy_Cost  Luxury_Status  \
0            A            1                 110.0            3.0   
1            A            2                 105.0            2.0   
2            A            3                  96.0            2.0   
3            A            4                  78.0            1.0   
4            A            5                 125.0            3.0   
5            B            1                 113.0            3.0   
6            B            2                 107.0            2.0   
7            B            3                 106.0            2.0   
8            B            4                 110.0            3.0   
9            B            5                   NaN            0.0   
10           C            1                  78.0            1.0   
11           C            2                  82.0            1.0   
12           C            3                  89.0            1.0   
13           C            4                  82.0            1.0   
14           C            5                  90.0            1.0   
15           D            1                  96.0            2.0   
16           D            2                  75.0            1.0   
17           D            3                 117.0            2.0   
18           D            4                 119.0            3.0   
19           D            5                 115.0            3.0   
20           E            1                 110.0            3.0   
21           E            2                  99.0            2.0   
22           E            3                  71.0            1.0   
23           E            4                 113.0            2.0   
24           E            5                   NaN            0.0   

    Room_Capacity  status  
0             2.0    True  
1             2.0    True  
2             2.0    True  
3             2.0    True  
4             3.0    True  
5             3.0    True  
6             2.0    True  
7             3.0    True  
8             2.0    True  
9             0.0   False  
10            2.0    True  
11            3.0    True  
12            3.0    True  
13            3.0    True  
14            2.0    True  
15            2.0    True  
16            2.0    True  
17            2.0    True  
18            2.0    True  
19            2.0    True  
20            3.0    True  
21            3.0    True  
22            2.0    True  
23            2.0    True  
24            0.0   False

# Creating the wing cost

# Create the initial metrices

0. Room ID metric

1. capacity metric

2. per room cost metric

3. wing cost

4. luxury status

In [116]:
# Room id metrics

room_id_metric = np.stack(hotel_df_processed.groupby('Wing_Number')['Room_Number'].apply(list))
room_id_metric = np.array(room_id_metric, dtype="float32")
room_id_metric

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]], dtype=float32)

In [117]:
# Room capacity metric

room_capacity_metric = np.stack(hotel_df_processed.groupby('Wing_Number')['Room_Capacity'].apply(list))
room_capacity_metric = np.array(room_capacity_metric, dtype="float32")
room_capacity_metric

array([[2., 2., 2., 2., 3.],
       [3., 2., 3., 2., 0.],
       [2., 3., 3., 3., 2.],
       [2., 2., 2., 2., 2.],
       [3., 3., 2., 2., 0.]], dtype=float32)

In [118]:
# per room cost metric

room_energy_metric = np.stack(hotel_df_processed.groupby('Wing_Number')['Per_Room_Energy_Cost'].apply(list))
room_energy_metric = np.array(room_energy_metric, dtype="float32")
room_energy_metric

array([[110., 105.,  96.,  78., 125.],
       [113., 107., 106., 110.,  nan],
       [ 78.,  82.,  89.,  82.,  90.],
       [ 96.,  75., 117., 119., 115.],
       [110.,  99.,  71., 113.,  nan]], dtype=float32)

In [119]:
wing_df

Wing_Number   Wing_Cost
0           A  342.830735
1           B  337.523495
2           C  328.270524
3           D  310.831277
4           E  308.469790

In [120]:
# per room cost metric

room_wing_cost_metric = np.stack(wing_df.groupby('Wing_Number')['Wing_Cost'].apply(list))
room_wing_cost_metric = np.array(room_wing_cost_metric , dtype="float32")
room_wing_cost_metric

array([[342.83075],
       [337.5235 ],
       [328.27054],
       [310.83127],
       [308.4698 ]], dtype=float32)

In [121]:
# luxury status

# per room cost metric

room_lux_metric = np.stack(hotel_df_processed.groupby('Wing_Number')['Luxury_Status'].apply(list))
room_lux_metric = np.array(room_lux_metric, dtype="float32")
room_lux_metric

array([[3., 2., 2., 1., 3.],
       [3., 2., 2., 3., 0.],
       [1., 1., 1., 1., 1.],
       [2., 1., 2., 3., 3.],
       [3., 2., 1., 2., 0.]], dtype=float32)

## Get the room and wing occupancies

In [122]:
room_capacity_metric.shape[0]

5

In [123]:
import numpy as np

# Create room_occupancy matrix
room_occupancy = np.zeros(room_capacity_metric.shape, dtype=int)

# Set the first row to be full of ones
room_occupancy[0, :] = 1

# Set the second to third rows with a mix of 1s and 0s
room_occupancy[1:room_capacity_metric.shape[0]-3, :] = np.random.choice([0, 1], size=(1, room_capacity_metric.shape[1]))

# Set the last row to be full of zeros
room_occupancy[room_capacity_metric.shape[0]-1, :] = 0

# Create wing_occupancy matrix as binary
wing_occupancy_binary = np.any(room_occupancy, axis=1).astype(int)

# Display the matrices
print("Room Occupancy Matrix:")
print(room_occupancy)

print("\nWing Occupancy Matrix:")
print(wing_occupancy_binary)


Room Occupancy Matrix:
[[1 1 1 1 1]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Wing Occupancy Matrix:
[1 1 0 0 0]


## Processing the metrices

In [124]:
room_occupancy[:7,]

array([[1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [125]:
room_occupancy.shape

(5, 5)

In [126]:
customer_cap
l_status
customer_cap

2

### making binary metrices

In [127]:
room_capacity_metric

array([[2., 2., 2., 2., 3.],
       [3., 2., 3., 2., 0.],
       [2., 3., 3., 3., 2.],
       [2., 2., 2., 2., 2.],
       [3., 3., 2., 2., 0.]], dtype=float32)

In [128]:
# Capacity processing
print('initlal room_capacity_metric')
print(room_capacity_metric)
room_capacity_metric_pr = np.where(room_capacity_metric >= customer_cap, 1, 0)
print('processed room_capacity_metric')
print(room_capacity_metric_pr)

initlal room_capacity_metric
[[2. 2. 2. 2. 3.]
 [3. 2. 3. 2. 0.]
 [2. 3. 3. 3. 2.]
 [2. 2. 2. 2. 2.]
 [3. 3. 2. 2. 0.]]
processed room_capacity_metric
[[1 1 1 1 1]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 0]]


In [129]:
# Luxury processing
print('initlal room_lux_metric')
print(room_lux_metric)
room_lux_metric_pr = np.where(room_lux_metric >= l_status, 1, 0)
print('processed room_capacity_metric')
print(room_lux_metric_pr)

initlal room_lux_metric
[[3. 2. 2. 1. 3.]
 [3. 2. 2. 3. 0.]
 [1. 1. 1. 1. 1.]
 [2. 1. 2. 3. 3.]
 [3. 2. 1. 2. 0.]]
processed room_capacity_metric
[[1 0 0 0 1]
 [1 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [1 0 0 0 0]]


### Inverting metrics

In [130]:
# Room occupancy

print('before_inverting')
print(room_occupancy)
room_occupancy_inv = ~room_occupancy.astype(bool)
room_occupancy_inv = room_occupancy_inv.astype(int)
print('after_inverting')
print(room_occupancy_inv)

before_inverting
[[1 1 1 1 1]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
after_inverting
[[0 0 0 0 0]
 [1 0 1 0 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [131]:
# wing occupancy

print('before_inverting')
print(wing_occupancy_binary)
wing_occupancy_binary_inv = ~wing_occupancy_binary.astype(bool)
wing_occupancy_binary_inv = wing_occupancy_binary_inv.astype(int)
print('after_inverting')
print(wing_occupancy_binary_inv)

before_inverting
[1 1 0 0 0]
after_inverting
[0 0 1 1 1]


### Defining the room cost

In [132]:
print(room_capacity_metric_pr.shape)
print(room_energy_metric.shape)
print(room_lux_metric_pr.shape)
print(room_occupancy_inv.shape)

(5, 5)
(5, 5)
(5, 5)
(5, 5)


In [133]:
room_energy_metric

array([[110., 105.,  96.,  78., 125.],
       [113., 107., 106., 110.,  nan],
       [ 78.,  82.,  89.,  82.,  90.],
       [ 96.,  75., 117., 119., 115.],
       [110.,  99.,  71., 113.,  nan]], dtype=float32)

In [134]:
cost_of_rooms = (
    room_capacity_metric_pr
    *room_energy_metric
    *room_lux_metric_pr
    *room_occupancy_inv
    )
cost_of_rooms

array([[  0.,   0.,   0.,   0.,   0.],
       [113.,   0.,   0.,   0.,  nan],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 119., 115.],
       [110.,   0.,   0.,   0.,  nan]])

In [135]:

cost_of_wings = (

       wing_occupancy_binary_inv.reshape(NUM_WINGS,1)
       *  room_wing_cost_metric
)

cost_of_wings

array([[  0.        ],
       [  0.        ],
       [328.27053833],
       [310.83126831],
       [308.4697876 ]])

In [136]:
cost_of_wings_pr = np.tile(cost_of_wings, (1, room_capacity_metric.shape[1]))
cost_of_wings_pr

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [328.27053833, 328.27053833, 328.27053833, 328.27053833,
        328.27053833],
       [310.83126831, 310.83126831, 310.83126831, 310.83126831,
        310.83126831],
       [308.4697876 , 308.4697876 , 308.4697876 , 308.4697876 ,
        308.4697876 ]])

In [137]:
final_cost_per_room = cost_of_rooms+cost_of_wings_pr
final_cost_per_room

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [113.        ,   0.        ,   0.        ,   0.        ,
                 nan],
       [328.27053833, 328.27053833, 328.27053833, 328.27053833,
        328.27053833],
       [310.83126831, 310.83126831, 310.83126831, 429.83126831,
        425.83126831],
       [418.4697876 , 308.4697876 , 308.4697876 , 308.4697876 ,
                 nan]])

In [138]:

flattened_array = final_cost_per_room.flatten()
non_zero_non_nan_indices = np.where(np.logical_and(flattened_array != 0, ~np.isnan(flattened_array)))

# Get the indices of the first 3 lowest values after excluding 0 and NaN
sorted_indices = np.argsort(flattened_array[non_zero_non_nan_indices])[:1]

# Convert the flattened indices to the original 2D indices
row_indices, col_indices = np.unravel_index(non_zero_non_nan_indices[0][sorted_indices], final_cost_per_room.shape)

# Get the values and positions
lowest_values = flattened_array[non_zero_non_nan_indices][sorted_indices]
positions = list(zip(row_indices, col_indices))

# Display the original array, flattened array, and result
print("Original Array:")
print(final_cost_per_room)


print("\nIndices of First 3 Lowest Values (excluding 0 and NaN):")
print(positions)

print("\nValues of First 3 Lowest Values (excluding 0 and NaN):", lowest_values)

Original Array:
[[  0.           0.           0.           0.           0.        ]
 [113.           0.           0.           0.                  nan]
 [328.27053833 328.27053833 328.27053833 328.27053833 328.27053833]
 [310.83126831 310.83126831 310.83126831 429.83126831 425.83126831]
 [418.4697876  308.4697876  308.4697876  308.4697876           nan]]

Indices of First 3 Lowest Values (excluding 0 and NaN):
[(1, 0)]

Values of First 3 Lowest Values (excluding 0 and NaN): [113.]


In [139]:
positions[0][1]

0

In [140]:
best_wing =np.array( wing_df[['Wing_Number']].sort_values(by= ['Wing_Number']).reset_index(drop=True))[positions[0][0]][0]
best_wing

'B'

In [141]:
best_room = positions[0][1]
best_room

0